include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_fields: false
    unused_import: false
    unused_field: false
    use_build_context_synchronously: false
    curly_braces_in_flow_control_structures: false

analyzer:
  errors:
    unused_import: ignore
    unused_field: ignore
    prefer_const_constructors: ignore
    prefer_final_fields: ignore
    use_build_context_synchronously: ignore
